### PR TITLE
Disable hotkeys when typing in a text area

### PR DESCRIPTION
**Pull request by e02d96ec16**
Discovered a new way to delete all my logs: by trying to write a feedback message! 😬

### CODE REVIEW

**Comment by motiko** [comment]
Thanks, mate. Sorry it happened to you.
Clearly remember fixing it before 😞 
Was it easy for you to find the fix?
I should add a build guide to the README..

**Comment by e02d96ec16** [comment]
Found it by chance, so not as terrible a trace to debug as it would have been if they just magically disappeared.

I was paranoid about where Feedback was sending the messages. As soon as I started typing, I saw a flurry of network traffic, all about my lovely logs being scrapped. From there on it was a matter of finding the key event listener with the Inspector, which I have no _real_ idea how to do, but eventually got to it through Ctrl+F _-ing_ the source more than anything.

I just edited this in GH; don't know enough for building stuff anyway.

UX-wise this is terrible I suppose. I don't recall even getting any feedback about the action.

**Comment by motiko** [comment]
I see, sorry again. 
Will update new version with the fix soon.

**Comment by e02d96ec16** [comment]
No worries! I haven't lost any _real_ logs. I was actually just going through my extensions, and had just discovered the new debug page. 😅

**Pull request merged**
